name: proyecto_festivdades
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vector1.png
    - assets/vector2.png
    - assets/vector3.png
    - assets/vector4.png
    - assets/vector5.png
    - assets/vector6.png
    - assets/vector7.png
    - assets/vector8.png
    - assets/im1.png
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
