// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1miMn-VgkRuRzFy_1o1HeyttXq7k-giQ',
    appId: '1:140641463376:web:25980aead1324b5f6cf555',
    messagingSenderId: '140641463376',
    projectId: 'proyecto-festividades',
    authDomain: 'proyecto-festividades.firebaseapp.com',
    storageBucket: 'proyecto-festividades.firebasestorage.app',
    measurementId: 'G-N69BN42HM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQoCMHXG_Yyd4d0QUXp8YXsV2zHx3T5U',
    appId: '1:140641463376:android:018b9b2ed2e6f27f6cf555',
    messagingSenderId: '140641463376',
    projectId: 'proyecto-festividades',
    storageBucket: 'proyecto-festividades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATw1Q-TbUCaA45c5cORgK44InnI-YxU9g',
    appId: '1:140641463376:ios:88df5c60002b3cc96cf555',
    messagingSenderId: '140641463376',
    projectId: 'proyecto-festividades',
    storageBucket: 'proyecto-festividades.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFestivdades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATw1Q-TbUCaA45c5cORgK44InnI-YxU9g',
    appId: '1:140641463376:ios:88df5c60002b3cc96cf555',
    messagingSenderId: '140641463376',
    projectId: 'proyecto-festividades',
    storageBucket: 'proyecto-festividades.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFestivdades',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1miMn-VgkRuRzFy_1o1HeyttXq7k-giQ',
    appId: '1:140641463376:web:fa0adc5896a66aea6cf555',
    messagingSenderId: '140641463376',
    projectId: 'proyecto-festividades',
    authDomain: 'proyecto-festividades.firebaseapp.com',
    storageBucket: 'proyecto-festividades.firebasestorage.app',
    measurementId: 'G-62MW3LPSGE',
  );
}
